"""initial schema: users, games, shelf_entries, reviews

Revision ID: bff45bbbb2c4
Revises: 
Create Date: 2026-07-29 19:03:55.599918

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'bff45bbbb2c4'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

# Managed explicitly rather than left to create_table. Postgres enum types
# outlive the table that uses them: autogenerate emits CREATE TYPE implicitly on
# the way up but no DROP TYPE on the way down, so `downgrade base` would leave
# shelf_status behind and the next `upgrade head` would fail with
# "type shelf_status already exists". create_type=False keeps create_table from
# creating it a second time.
shelf_status = postgresql.ENUM(
    'want_to_play', 'playing', 'completed', 'on_hold', 'dropped',
    name='shelf_status',
    create_type=False,
)


def upgrade() -> None:
    """Upgrade schema."""
    shelf_status.create(op.get_bind(), checkfirst=True)
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('games',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('rawg_id', sa.Integer(), nullable=False),
    sa.Column('slug', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('background_image', sa.String(length=500), nullable=True),
    sa.Column('released', sa.Date(), nullable=True),
    sa.Column('metacritic', sa.Integer(), nullable=True),
    sa.Column('rawg_rating', sa.Float(), nullable=True),
    sa.Column('playtime_hours', sa.Integer(), nullable=True),
    sa.Column('genres', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('platforms', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('developers', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('synced_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_games_name'), 'games', ['name'], unique=False)
    op.create_index(op.f('ix_games_rawg_id'), 'games', ['rawg_id'], unique=True)
    op.create_index(op.f('ix_games_slug'), 'games', ['slug'], unique=True)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('bio', sa.String(length=500), nullable=True),
    sa.Column('avatar_url', sa.String(length=500), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('reviews',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('game_id', sa.Integer(), nullable=False),
    sa.Column('rating', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=True),
    sa.Column('body', sa.Text(), nullable=True),
    sa.Column('contains_spoilers', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('rating BETWEEN 1 AND 10', name='ck_reviews_rating_range'),
    sa.ForeignKeyConstraint(['game_id'], ['games.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'game_id', name='uq_reviews_user_game')
    )
    op.create_index(op.f('ix_reviews_game_id'), 'reviews', ['game_id'], unique=False)
    op.create_index(op.f('ix_reviews_user_id'), 'reviews', ['user_id'], unique=False)
    op.create_table('shelf_entries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('game_id', sa.Integer(), nullable=False),
    sa.Column('status', shelf_status, nullable=False),
    sa.Column('hours_played', sa.Numeric(precision=6, scale=1), nullable=True),
    sa.Column('platform', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('started_on', sa.Date(), nullable=True),
    sa.Column('finished_on', sa.Date(), nullable=True),
    sa.Column('replay_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('hours_played >= 0', name='ck_shelf_entries_hours_non_negative'),
    sa.ForeignKeyConstraint(['game_id'], ['games.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'game_id', name='uq_shelf_entries_user_game')
    )
    op.create_index(op.f('ix_shelf_entries_game_id'), 'shelf_entries', ['game_id'], unique=False)
    op.create_index(op.f('ix_shelf_entries_status'), 'shelf_entries', ['status'], unique=False)
    op.create_index(op.f('ix_shelf_entries_user_id'), 'shelf_entries', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_shelf_entries_user_id'), table_name='shelf_entries')
    op.drop_index(op.f('ix_shelf_entries_status'), table_name='shelf_entries')
    op.drop_index(op.f('ix_shelf_entries_game_id'), table_name='shelf_entries')
    op.drop_table('shelf_entries')
    op.drop_index(op.f('ix_reviews_user_id'), table_name='reviews')
    op.drop_index(op.f('ix_reviews_game_id'), table_name='reviews')
    op.drop_table('reviews')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_games_slug'), table_name='games')
    op.drop_index(op.f('ix_games_rawg_id'), table_name='games')
    op.drop_index(op.f('ix_games_name'), table_name='games')
    op.drop_table('games')
    # ### end Alembic commands ###
    shelf_status.drop(op.get_bind(), checkfirst=True)
